services:
  db:
    image: postgres:15.0-alpine3.16
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-jsonb-test-data:/var/lib/postgresql/data

networks:
  backend: {}

volumes:
  postgres-jsonb-test-data: